## Perform BackPropogation Using Pytorch

x^n------->Derivatives ------->n*x^n-1

y = x^2

dy/dx = 2x

In [60]:
import torch


In [61]:
x = torch.tensor(4.0,requires_grad=True)

In [62]:
print(x.grad)

None


In [63]:
y = x**2

In [64]:
y

tensor(16., grad_fn=<PowBackward0>)

Backpropogation y = 2*x

In [65]:
y.backward()

In [66]:
print(x.grad)

tensor(8.)


In [68]:
lst = [[2.,3.,1.],[4.,5.,3.],[7.,6.,4.]]
torch_input = torch.tensor(lst, requires_grad=True)

In [69]:
torch_input

tensor([[2., 3., 1.],
        [4., 5., 3.],
        [7., 6., 4.]], requires_grad=True)

In [70]:
#y=x**3 + x**2
y = torch_input**3 + torch_input**2

In [71]:
y

tensor([[ 12.,  36.,   2.],
        [ 80., 150.,  36.],
        [392., 252.,  80.]], grad_fn=<AddBackward0>)

In [72]:
z = y.sum()

In [73]:
z

tensor(1040., grad_fn=<SumBackward0>)

In [74]:
#Lets do here Backpropogation
z.backward()

In [75]:
print(torch_input.grad)

tensor([[ 16.,  33.,   5.],
        [ 56.,  85.,  33.],
        [161., 120.,  56.]])
