A tensor is a generalization of vectors and matrics and easily understood the multi dimentional array. It is tearm and set of techniques known in machine learning in the training operation of deep learning models can be describe in terms of tensors.

In many cases, tensors are used as a replacement of numpy to use the power of GPU.

Tensors are the type of data structure used in Linear algebra, and like vectors and matrices, ypu can calculate arthimatic operation with tensors.

In [ ]:
import torch

In [3]:
import numpy as np

In [4]:
lst = [1,2,3,4,5]
arr = np.array(lst)

In [5]:
arr.dtype

dtype('int64')

## Convert numpy into PyTorch tensors

In [6]:
tensors = torch.from_numpy(arr)

In [7]:
tensors

tensor([1, 2, 3, 4, 5])

In [8]:
tensors.dtype

torch.int64

In [12]:
#indexing similer to numpy
tensors[:2]

tensor([1, 2])

In [17]:
#Range 
tensors[:5]

tensor([1, 2, 3, 4, 5])

In [16]:
arr

array([1, 2, 3, 4, 5])

Here tensor uses same memory of numpy

So to prevent by tensor this by tensor torch

In [24]:
tensors_arr = torch.tensor(arr)
tensors_arr

tensor([1, 2, 3, 4, 5])

In [25]:
tensors_arr[3] = 200

In [26]:
tensors_arr

tensor([  1,   2,   3, 200,   5])

In [27]:
arr

array([1, 2, 3, 4, 5])

Now we can see that, we updated the tensor_arr and there is no change in arr

## Arthimatic Operation

In [33]:
a = torch.tensor([3,4,5], dtype = torch.float)
b = torch.tensor([6,7,8], dtype = torch.float)

In [34]:
print(a)
print(b)

tensor([3., 4., 5.])
tensor([6., 7., 8.])


In [35]:
torch.add(a,b)

tensor([ 9., 11., 13.])

In [38]:
print(a+b)

tensor([ 9., 11., 13.])


In [39]:
c = torch.zeros(3)

In [40]:
c

tensor([0., 0., 0.])

In [41]:
torch.add(a,b, out = c)

tensor([ 9., 11., 13.])

In [42]:
c

tensor([ 9., 11., 13.])

In [44]:
torch.add(a,b).sum()

tensor(33.)

## Dot product and Multiplication Operation

In [45]:
x = torch.tensor([3,4,5], dtype = torch.float)
y = torch.tensor([6,7,8], dtype = torch.float)

In [47]:
x.mul(y)

tensor([18., 28., 40.])

In [48]:
(3*6)+(4*7)+(5*8)
x.dot(y)

tensor(86.)

## martix multiplication

In [59]:
x = torch.tensor([[1,4,2],[1,5,5]], dtype = torch.float)
y = torch.tensor([[6,7],[8,6],[9,11]], dtype = torch.float)

In [60]:
torch.matmul(x,y)

tensor([[56., 53.],
        [91., 92.]])

In [61]:
torch.mm(x,y, out =c)

tensor([[56., 53.],
        [91., 92.]])

In [62]:
x@y

tensor([[56., 53.],
        [91., 92.]])

## Converting NumPy Array to Torch Tensor


In [64]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## Tensors can be moved onto any device using the .to method.



In [66]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

## AUTOGRAD: AUTOMATIC DIFFERENTIATION


autograd provides automatic differentiation for all the operation on Tensors. This helps us to do backpropogation at runtime at every single iteration. 

If you set its attribute .requires_grad as True, it starts to track all operations on it. When you finish your computation you can call .backward() and have all the gradients computed automatically. The gradient for this tensor will be accumulated into .grad attribute.

To stop a tensor from tracking history, you can call .detach() to detach it from the computation history, and to prevent future computation from being tracked.

Whenwe dont need gradients, then "with torch.no_grad():" to prevent tracking history and using memory

There’s one more class which is very important for autograd implementation - <b>a Function</b>.



<b>Tensor</b> and <b>Function</b> are interconnected and build up an acyclic graph, that encodes a complete history of computation. Each tensor has a <b>.grad_fn</b> attribute that references a Function that has created the Tensor (except for Tensors created by the user - their grad_fn is None).

We can compute the derivatives, you can call <b>.backward()</b> on a Tensor.



In [67]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [68]:
#Now we can perform tensor operation
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [69]:
# y was created as a result of an operation, so it has a grad_fn.

print(y.grad_fn)


In [70]:
#Do more operations on y

z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [71]:
# .requires_grad_( ... ) changes an existing Tensor’s requires_grad flag in-place. The input flag defaults to False if not given.

a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


## Gradients

Let’s backprop now. Because out contains a single scalar, out.backward() is equivalent to out.backward(torch.tensor(1.)).

In [72]:
out.backward()


In [73]:
# Print gradients d(out)/dx

print(x.grad)


tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [74]:
# You can also stop autograd from tracking history on Tensors with .requires_grad=True either by wrapping the code block in with torch.no_grad():

print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


In [75]:
# Or by using .detach() to get a new Tensor with the same content but that does not require gradients:

print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)
